const extraCourses = {
  cybersec:{title:"Bảo mật Thông tin",level:"intermediate",cat:"technology",icon:"🔒",img:"cybersec.png",desc:"Học cách bảo vệ hệ thống, mạng và dữ liệu khỏi các mối đe dọa mạng hiện đại.",benefits:["Nắm vững các loại tấn công mạng phổ biến","Cài đặt firewall và hệ thống phát hiện xâm nhập","Thực hành kiểm tra bảo mật (Penetration Testing)"],modules:[{title:"Cybersecurity Fundamentals",duration:"30 giờ",questions:[{q:"Mã hóa đối xứng là gì?",options:["Dùng 2 khóa khác nhau","Dùng cùng khóa để mã hóa/giải mã","Không dùng khóa","Dùng mã QR"],a:1},{q:"Tấn công Phishing nhắm vào yếu tố nào?",options:["Phần cứng","Con người","Router","Database"],a:1},{q:"HTTPS bảo vệ dữ liệu bằng giao thức nào?",options:["FTP","SSH","TLS/SSL","HTTP"],a:2},{q:"Firewall hoạt động ở tầng nào của OSI?",options:["Tầng 1","Tầng 3-4","Tầng 7","Tầng 2"],a:1},{q:"SQL Injection tấn công vào đâu?",options:["Giao diện web","Cơ sở dữ liệu","RAM","CPU"],a:1},{q:"2FA là viết tắt của gì?",options:["Two Factor Authentication","Two File Access","Transfer File Algorithm","Two Function App"],a:0},{q:"VPN giúp gì cho người dùng?",options:["Tăng tốc internet","Ẩn địa chỉ IP và mã hóa kết nối","Diệt virus","Chặn quảng cáo"],a:1},{q:"Zero-day vulnerability là gì?",options:["Lỗ hổng đã có bản vá","Lỗ hổng chưa được vá","Virus máy tính","Phần mềm độc hại"],a:1}]}]},
  cloud:{title:"Cloud Computing AWS",level:"intermediate",cat:"technology",icon:"☁️",img:"cloud.png",desc:"Làm chủ điện toán đám mây với Amazon Web Services - nền tảng cloud hàng đầu thế giới.",benefits:["Hiểu kiến trúc cloud và các mô hình dịch vụ IaaS/PaaS/SaaS","Triển khai ứng dụng trên EC2, S3, RDS","Chuẩn bị cho chứng chỉ AWS Cloud Practitioner"],modules:[{title:"AWS Cloud Fundamentals",duration:"35 giờ",questions:[{q:"IaaS là gì?",options:["Internet as a Service","Infrastructure as a Service","Integration as a Service","Intelligent as a Service"],a:1},{q:"S3 trong AWS dùng để làm gì?",options:["Lưu trữ đối tượng (Object Storage)","Máy chủ ảo","Database","Email"],a:0},{q:"EC2 là dịch vụ gì?",options:["Email","Máy chủ ảo (Virtual Machine)","Storage","CDN"],a:1},{q:"Mô hình chia sẻ trách nhiệm của AWS có nghĩa là gì?",options:["AWS chịu trách nhiệm mọi thứ","Khách hàng chịu tất cả","AWS quản lý hạ tầng, khách hàng quản lý dữ liệu","Không ai chịu trách nhiệm"],a:2},{q:"Region trong AWS là gì?",options:["Một máy chủ","Vùng địa lý chứa nhiều data center","Loại dịch vụ","Gói cước"],a:1},{q:"Auto Scaling giúp gì?",options:["Tự động tăng/giảm tài nguyên theo nhu cầu","Tự động xóa dữ liệu","Tự động backup","Tự động gửi email"],a:0},{q:"Load Balancer dùng để làm gì?",options:["Cân bằng tải giữa nhiều server","Cân bằng điện","Lưu trữ dữ liệu","Mã hóa"],a:0},{q:"Serverless computing nghĩa là gì?",options:["Không có server vật lý nào","Chạy code mà không cần quản lý server","Máy tính không có nguồn điện","Lập trình không cần code"],a:1}]}]},
  devops:{title:"DevOps & CI/CD",level:"advanced",cat:"technology",icon:"⚙️",img:"devops.png",desc:"Tích hợp phát triển và vận hành phần mềm với các công cụ DevOps hiện đại.",benefits:["Xây dựng pipeline CI/CD tự động với GitHub Actions","Container hóa ứng dụng với Docker và Kubernetes","Giám sát hệ thống với Grafana và Prometheus"],modules:[{title:"DevOps Essentials",duration:"40 giờ",questions:[{q:"CI/CD viết tắt của gì?",options:["Continuous Integration/Continuous Deployment","Computer Interface/Code Design","Central Index/Content Delivery","None"],a:0},{q:"Docker image khác container ở điểm nào?",options:["Image là bản chạy, container là template","Image là template, container là bản chạy","Giống nhau","Image lớn hơn"],a:1},{q:"Kubernetes dùng để làm gì?",options:["Viết code","Điều phối container","Thiết kế database","Tạo UI"],a:1},{q:"Git là gì?",options:["Ngôn ngữ lập trình","Hệ thống quản lý phiên bản","Database","Web server"],a:1},{q:"Infrastructure as Code (IaC) có nghĩa là gì?",options:["Quản lý hạ tầng bằng code/script","Viết code trên cloud","Hạ tầng không cần code","Code chạy trên phần cứng"],a:0},{q:"Blue-Green Deployment là kỹ thuật gì?",options:["Triển khai với 2 môi trường để giảm downtime","Dùng màu xanh trong UI","Loại database","Phương pháp test"],a:0},{q:"Monitoring trong DevOps quan trọng vì?",options:["Phát hiện vấn đề sớm trước khi ảnh hưởng người dùng","Làm đẹp dashboard","Tăng tốc code","Tiết kiệm điện"],a:0},{q:"Microservices khác Monolithic ở điểm gì?",options:["Chia nhỏ thành các dịch vụ độc lập vs một khối lớn","Microservices nhỏ hơn về file size","Monolithic nhanh hơn","Không khác nhau"],a:0}]}]},
  uxui:{title:"UI/UX Design với Figma",level:"basic",cat:"design",icon:"🎨",img:"uxui.png",desc:"Thiết kế giao diện người dùng chuyên nghiệp với công cụ Figma hàng đầu ngành.",benefits:["Nắm vững nguyên tắc thiết kế UI/UX hiện đại","Thành thạo Figma: Prototype, Component, Auto Layout","Xây dựng Design System và Handoff cho developer"],modules:[{title:"UI/UX Fundamentals",duration:"25 giờ",questions:[{q:"UX là viết tắt của gì?",options:["User Experience","User Extension","Ultra Experience","Unique Exchange"],a:0},{q:"Wireframe dùng để làm gì?",options:["Vẽ tranh nghệ thuật","Phác thảo bố cục giao diện","Viết code","Chụp ảnh"],a:1},{q:"Design System là gì?",options:["Hệ điều hành","Tập hợp các component và quy tắc thiết kế thống nhất","Phần mềm thiết kế","Kiểu máy tính"],a:1},{q:"Prototype trong Figma dùng để làm gì?",options:["In bản vẽ","Mô phỏng tương tác của sản phẩm thực","Viết code tự động","Quản lý file"],a:1},{q:"Color contrast quan trọng cho điều gì?",options:["Thẩm mỹ","Accessibility - khả năng tiếp cận cho người dùng khiếm thị","Tốc độ tải trang","Bảo mật"],a:1},{q:"Responsive Design là gì?",options:["Thiết kế nhanh","Giao diện tự thích ứng với mọi kích thước màn hình","Thiết kế có animation","Thiết kế 3D"],a:1},{q:"Heuristic Evaluation đánh giá điều gì?",options:["Màu sắc","Tính dễ sử dụng của giao diện theo 10 nguyên tắc","Tốc độ render","Code quality"],a:1},{q:"A/B Testing trong thiết kế là gì?",options:["So sánh 2 phiên bản để xem phiên bản nào tốt hơn","Test bảng chữ cái","Kiểm tra phần cứng","Test màu sắc"],a:0}]}]},
  marketing:{title:"Digital Marketing",level:"basic",cat:"marketing",icon:"📱",img:"marketing.png",desc:"Chiến lược marketing kỹ thuật số toàn diện: SEO, Social Media, Email, và Paid Ads.",benefits:["Xây dựng chiến lược digital marketing từ đầu","Thành thạo Google Analytics và đo lường hiệu quả","Chạy quảng cáo Google Ads và Facebook Ads hiệu quả"],modules:[{title:"Digital Marketing Basics",duration:"20 giờ",questions:[{q:"SEO viết tắt của gì?",options:["Search Engine Optimization","Social Engine Operations","Sales Enhancement Online","System Entry Options"],a:0},{q:"CTR là chỉ số gì?",options:["Click-Through Rate","Customer Tracking Record","Content Transfer Rate","Conversion Total Report"],a:0},{q:"KPI trong marketing dùng để làm gì?",options:["Đo lường hiệu suất chiến dịch","Thiết kế banner","Lập trình web","Quản lý nhân sự"],a:0},{q:"Content Marketing nhắm vào mục tiêu nào?",options:["Quảng cáo trả phí","Thu hút khách hàng qua nội dung giá trị","Spam email","Gọi điện telesales"],a:1},{q:"Funnel marketing gồm các giai đoạn nào?",options:["Awareness-Interest-Desire-Action","Buy-Sell-Return","Click-View-Share","Like-Comment-Share"],a:0},{q:"Retargeting là kỹ thuật gì?",options:["Nhắm lại những người đã tương tác với brand","Target ngẫu nhiên","Gửi email hàng loạt","Spam quảng cáo"],a:0},{q:"Organic traffic là gì?",options:["Traffic từ quảng cáo trả phí","Traffic tự nhiên từ SEO/không phải quảng cáo","Traffic từ mạng xã hội","Traffic từ email"],a:1},{q:"ROI trong marketing tính như thế nào?",options:["(Doanh thu - Chi phí) / Chi phí x 100%","Doanh thu / Số click","Chi phí x Lợi nhuận","Không có công thức"],a:0}]}]},
  finance:{title:"Đầu tư Chứng khoán",level:"intermediate",cat:"finance",icon:"📈",img:"finance.png",desc:"Hiểu thị trường chứng khoán, phân tích cổ phiếu và xây dựng danh mục đầu tư sinh lời.",benefits:["Nắm vững nguyên tắc phân tích kỹ thuật và cơ bản","Xây dựng danh mục đầu tư đa dạng hóa rủi ro","Hiểu tâm lý thị trường và kiểm soát cảm xúc đầu tư"],modules:[{title:"Stock Market Fundamentals",duration:"25 giờ",questions:[{q:"P/E Ratio là chỉ số gì?",options:["Price to Earnings - Giá trên lợi nhuận mỗi cổ phiếu","Profit to Equity","Price to Equity","Production Efficiency"],a:0},{q:"Blue chip stock là gì?",options:["Cổ phiếu màu xanh","Cổ phiếu của công ty lớn uy tín, ổn định","Cổ phiếu giá rẻ","Cổ phiếu công nghệ"],a:1},{q:"Đa dạng hóa danh mục (Diversification) giúp gì?",options:["Tăng lợi nhuận tối đa","Giảm rủi ro tổng thể","Đảm bảo không lỗ","Không có tác dụng"],a:1},{q:"Bull market nghĩa là gì?",options:["Thị trường giảm mạnh","Thị trường tăng trưởng","Thị trường ổn định","Thị trường bò"],a:1},{q:"Dividend là gì?",options:["Phí giao dịch","Cổ tức - phần lợi nhuận chia cho cổ đông","Thuế đầu tư","Phí quản lý quỹ"],a:1},{q:"Stop-loss dùng để làm gì?",options:["Dừng lỗ tự động khi giá xuống mức nhất định","Dừng lợi nhuận","Khóa tài khoản","Thoát lệnh mua"],a:0},{q:"ETF là gì?",options:["Electronic Transfer Fund","Exchange Traded Fund - Quỹ giao dịch trên sàn","Energy Technology Finance","Enterprise Trading Framework"],a:1},{q:"Phân tích kỹ thuật dựa vào đâu?",options:["Báo cáo tài chính","Lịch sử giá và khối lượng giao dịch","Tin tức kinh tế","Ý kiến chuyên gia"],a:1}]}]},
  excel:{title:"Excel Nâng cao & Power BI",level:"intermediate",cat:"data",icon:"📊",img:"excel.png",desc:"Làm chủ Excel từ cơ bản đến nâng cao và trực quan hóa dữ liệu với Power BI.",benefits:["Thành thạo các hàm Excel: VLOOKUP, INDEX, MATCH, PIVOT","Tự động hóa công việc với Macro và VBA","Xây dựng dashboard đẹp và tương tác với Power BI"],modules:[{title:"Excel & Power BI Mastery",duration:"20 giờ",questions:[{q:"Hàm VLOOKUP dùng để làm gì?",options:["Tính tổng","Tìm kiếm giá trị theo chiều dọc","Tạo biểu đồ","Lọc dữ liệu"],a:1},{q:"Pivot Table dùng để làm gì?",options:["Tạo công thức","Tóm tắt và phân tích dữ liệu lớn","Vẽ biểu đồ","In bảng tính"],a:1},{q:"Hàm IF trong Excel trả về gì?",options:["Luôn trả về số","Giá trị dựa trên điều kiện đúng/sai","Chuỗi văn bản","Ngày tháng"],a:1},{q:"Power Query dùng để làm gì?",options:["Viết code Python","Kết nối, làm sạch và biến đổi dữ liệu","Tạo presentation","Gửi email"],a:1},{q:"DAX trong Power BI là gì?",options:["Ngôn ngữ lập trình web","Ngôn ngữ biểu thức phân tích dữ liệu","Database server","Design Application"],a:1},{q:"Conditional Formatting dùng để làm gì?",options:["Định dạng ô theo điều kiện dữ liệu","In màu printer","Thay đổi font","Tạo hyperlink"],a:0},{q:"SUMIF khác SUM ở điểm nào?",options:["Nhanh hơn SUM","Chỉ tính tổng các ô thỏa điều kiện","Tính tổng toàn bộ","Không khác gì"],a:1},{q:"Shortcut Ctrl+Shift+L trong Excel làm gì?",options:["Lưu file","Bật/tắt AutoFilter","In file","Mở file mới"],a:1}]}]},
  english:{title:"Tiếng Anh Giao tiếp Thương mại",level:"basic",cat:"language",icon:"🗣️",img:"english.png",desc:"Nắm vững tiếng Anh giao tiếp trong môi trường kinh doanh quốc tế chuyên nghiệp.",benefits:["Tự tin giao tiếp email và họp hành bằng tiếng Anh","Viết báo cáo và thuyết trình chuyên nghiệp","Chuẩn bị cho phỏng vấn việc làm bằng tiếng Anh"],modules:[{title:"Business English",duration:"30 giờ",questions:[{q:"'I look forward to hearing from you' dùng trong tình huống nào?",options:["Kết thúc email trang trọng","Lời chào khi gặp mặt","Từ chối đề nghị","Xin việc bằng miệng"],a:0},{q:"'Could you please...' thể hiện điều gì?",options:["Mệnh lệnh","Yêu cầu lịch sự","Câu hỏi về khả năng","Từ chối"],a:1},{q:"Email chuyên nghiệp thường bắt đầu bằng gì?",options:["Hey!","Yo!","Dear Mr/Ms [Name]","What's up"],a:2},{q:"'Let's touch base' nghĩa là gì?",options:["Chạm vào đáy","Hãy liên lạc/gặp nhau","Đụng chân","Nghỉ giải lao"],a:1},{q:"Meeting agenda là gì?",options:["Biên bản họp","Chương trình nghị sự cuộc họp","Danh sách tham dự","Kết quả họp"],a:1},{q:"'Please find attached' dùng khi nào?",options:["Khi tìm kiếm file","Khi gửi file đính kèm","Khi yêu cầu gặp mặt","Khi từ chối"],a:1},{q:"KPI báo cáo thường dùng từ nào?",options:["Exceed / Meet / Miss targets","Happy / Sad / OK","Big / Small / Medium","Fast / Slow / Normal"],a:0},{q:"Phong cách viết email trang trọng (formal) tránh gì?",options:["Từ kỹ thuật","Viết tắt và ngôn ngữ thân mật","Đoạn dài","Ký tên"],a:1}]}]},
  project:{title:"Quản lý Dự án (PMP)",level:"intermediate",cat:"business",icon:"📋",img:"project.png",desc:"Nắm vững phương pháp quản lý dự án PMI và chuẩn bị cho chứng chỉ PMP quốc tế.",benefits:["Hiểu các nhóm quy trình và vùng kiến thức trong PMBOK","Lập kế hoạch, giám sát và kiểm soát dự án hiệu quả","Chuẩn bị kiến thức thi chứng chỉ PMP","Áp dụng Agile/Scrum trong quản lý dự án hiện đại"],modules:[{title:"Project Management Fundamentals",duration:"35 giờ",questions:[{q:"WBS là viết tắt của gì?",options:["Work Breakdown Structure","Web Based System","Weekly Budget Summary","Work Based Schedule"],a:0},{q:"Critical Path Method (CPM) dùng để làm gì?",options:["Xác định con đường ngắn nhất trong mạng lưới công việc ảnh hưởng thời gian dự án","Tìm lỗi trong code","Quản lý ngân sách","Phân công nhân sự"],a:0},{q:"Stakeholder là ai?",options:["Chỉ là khách hàng","Tất cả những bên liên quan và bị ảnh hưởng bởi dự án","Chỉ là nhà đầu tư","Chỉ là nhóm dự án"],a:1},{q:"Scrum Sprint thường kéo dài bao lâu?",options:["6 tháng","1-4 tuần","1 năm","1 ngày"],a:1},{q:"Risk Matrix dùng để làm gì?",options:["Đánh giá rủi ro theo xác suất và tác động","Ma trận nhân sự","Bảng tính chi phí","Lịch họp"],a:0},{q:"Agile khác Waterfall ở điểm gì chính?",options:["Agile linh hoạt theo vòng lặp, Waterfall tuần tự cố định","Agile nhanh hơn","Waterfall tốt hơn","Không khác nhau"],a:0},{q:"Baseline trong quản lý dự án là gì?",options:["Đường cơ sở để so sánh tiến độ thực tế","Nền tảng phần mềm","Hệ thống cơ sở dữ liệu","Vạch xuất phát"],a:0},{q:"Lessons Learned thực hiện khi nào?",options:["Khi bắt đầu dự án","Trong suốt và cuối dự án","Chỉ khi thất bại","Không bao giờ"],a:1}]}]},
  photoshop:{title:"Adobe Photoshop & Illustrator",level:"basic",cat:"design",icon:"🖼️",img:"photoshop.png",desc:"Làm chủ 2 phần mềm thiết kế hàng đầu của Adobe để tạo ra các sản phẩm đồ họa chuyên nghiệp.",benefits:["Chỉnh sửa ảnh chuyên nghiệp với Photoshop","Thiết kế logo và nhận diện thương hiệu với Illustrator","Xuất file đúng chuẩn cho in ấn và kỹ thuật số"],modules:[{title:"Adobe Creative Suite",duration:"30 giờ",questions:[{q:"Vector graphic khác Raster ở điểm nào?",options:["Vector dùng điểm ảnh, Raster dùng toán học","Vector dùng toán học nên không vỡ khi phóng to","Giống nhau","Vector nhỏ hơn"],a:1},{q:"CMYK dùng trong thiết kế nào?",options:["Thiết kế web","Thiết kế dành cho in ấn","Video","Social media"],a:1},{q:"Layer Mask trong Photoshop dùng để làm gì?",options:["Tạo layer mới","Ẩn/hiện vùng ảnh mà không xóa vĩnh viễn","Đổi màu ảnh","Cắt ảnh"],a:1},{q:"DPI là gì?",options:["Digital Pixel Interface","Dots Per Inch - Độ phân giải in ấn","Design Per Image","Data Processing Index"],a:1},{q:"Smart Object trong Photoshop có lợi ích gì?",options:["Làm ảnh nặng hơn","Cho phép chỉnh sửa không phá hủy","Xóa layer","In nhanh hơn"],a:1},{q:"Pen Tool dùng để làm gì?",options:["Viết chữ","Vẽ đường và hình dạng vector chính xác","Tẩy xóa","Cắt ảnh"],a:1},{q:"RGB là viết tắt của gì?",options:["Red Green Blue","Real Graphic Base","Render Graphic Bitmap","None"],a:0},{q:"Blending Mode trong Photoshop là gì?",options:["Chế độ hòa trộn layer ảnh hưởng màu sắc","Công cụ trộn màu","Cách export file","Loại filter"],a:0}]}]}
};

// === PART 2: 10 more courses ===
const extraCourses2 = {
  flutter:{title:"Lập trình Mobile Flutter",level:"intermediate",cat:"technology",icon:"📱",img:"flutter.png",desc:"Xây dựng ứng dụng di động iOS và Android đồng thời bằng Flutter và ngôn ngữ Dart.",benefits:["Tạo app di động đẹp chạy cả iOS lẫn Android","Nắm vững Widget tree và State management","Kết nối API và tích hợp Firebase"],modules:[{title:"Flutter Development",duration:"40 giờ",questions:[{q:"Flutter dùng ngôn ngữ lập trình nào?",options:["JavaScript","Kotlin","Dart","Swift"],a:2},{q:"Widget trong Flutter là gì?",options:["Thành phần UI cơ bản","Plugin","Database","API"],a:0},{q:"StatefulWidget khác StatelessWidget ở điểm nào?",options:["StatefulWidget có thể thay đổi state, StatelessWidget không","Giống nhau","StatelessWidget nhanh hơn","StatefulWidget nhỏ hơn"],a:0},{q:"pubspec.yaml dùng để làm gì?",options:["Viết code Dart","Khai báo dependencies và assets của project","Cấu hình database","Thiết kế UI"],a:1},{q:"Hot Reload trong Flutter giúp gì?",options:["Xóa app","Xem thay đổi code ngay lập tức mà không cần khởi động lại","Tăng tốc app","Giảm dung lượng"],a:1},{q:"Navigator trong Flutter dùng để làm gì?",options:["Định vị GPS","Điều hướng giữa các màn hình","Quản lý state","Kết nối API"],a:1},{q:"FutureBuilder dùng khi nào?",options:["Luôn dùng","Khi cần hiển thị dữ liệu bất đồng bộ","Tạo animation","Thiết kế layout"],a:1},{q:"Provider là gì trong Flutter?",options:["Nhà cung cấp dịch vụ","State management solution phổ biến","Widget","Plugin camera"],a:1}]}]},
  blockchain:{title:"Blockchain & Web3",level:"advanced",cat:"technology",icon:"⛓️",img:"blockchain.png",desc:"Khám phá công nghệ blockchain, hợp đồng thông minh và phát triển ứng dụng Web3.",benefits:["Hiểu cơ chế hoạt động của blockchain và cryptocurrency","Viết Smart Contract với Solidity","Xây dựng DApp đơn giản trên Ethereum"],modules:[{title:"Blockchain Fundamentals",duration:"35 giờ",questions:[{q:"Blockchain là gì?",options:["Chuỗi khối dữ liệu phân tán và bất biến","Loại database truyền thống","Phần mềm ngân hàng","Ngôn ngữ lập trình"],a:0},{q:"Smart Contract là gì?",options:["Hợp đồng giấy tờ","Code tự thực thi trên blockchain khi điều kiện thỏa mãn","Email tự động","App di động"],a:1},{q:"Consensus mechanism trong blockchain dùng để làm gì?",options:["Trang trí giao diện","Đồng thuận về trạng thái của blockchain giữa các node","Mã hóa dữ liệu","Tăng tốc giao dịch"],a:1},{q:"Gas fee trong Ethereum là gì?",options:["Phí xăng dầu","Phí trả cho miner/validator để xử lý giao dịch","Loại token","Phí rút tiền"],a:1},{q:"NFT là viết tắt của gì?",options:["New Functional Token","Non-Fungible Token","Network File Transfer","Node Function Test"],a:1},{q:"DeFi nghĩa là gì?",options:["Defined Finance","Decentralized Finance - Tài chính phi tập trung","Default Finance","Digital Finance"],a:1},{q:"Solidity là ngôn ngữ dùng cho mục đích gì?",options:["Lập trình web","Viết Smart Contract trên Ethereum","Machine Learning","Mobile App"],a:1},{q:"Wallet address trong crypto có đặc điểm gì?",options:["Ngắn và dễ nhớ","Chuỗi ký tự dài duy nhất đại diện cho tài khoản","Số điện thoại","Email"],a:1}]}]},
  videoediting:{title:"Dựng phim & Video Editing",level:"basic",cat:"design",icon:"🎬",img:"videoediting.png",desc:"Học dựng phim chuyên nghiệp với Adobe Premiere Pro và kỹ năng kể chuyện bằng hình ảnh.",benefits:["Thành thạo timeline và các công cụ cắt ghép trong Premiere Pro","Áp dụng color grading và âm thanh chuyên nghiệp","Xuất video đúng chuẩn cho YouTube, TikTok, TV"],modules:[{title:"Video Production",duration:"25 giờ",questions:[{q:"Frame rate (fps) phổ biến cho video online là gì?",options:["12fps","24/30fps","60fps","120fps"],a:1},{q:"Cut trong dựng phim là gì?",options:["Xóa video","Chuyển cảnh đột ngột","Làm mờ","Thêm nhạc"],a:1},{q:"B-roll là gì?",options:["Video phụ bổ sung cho nội dung chính","Video lỗi","Phần nhạc nền","Tên phần mềm"],a:0},{q:"Color grading dùng để làm gì?",options:["Sửa lỗi màu sắc","Điều chỉnh tông màu để tạo cảm xúc và phong cách","Thêm chữ","Cắt video"],a:1},{q:"Codec là gì?",options:["Phần cứng máy tính","Thuật toán nén/giải nén video","Phần mềm dựng phim","Loại file"],a:1},{q:"Timeline trong Premiere Pro là gì?",options:["Bảng màu","Khu vực sắp xếp và chỉnh sửa các clip","Thư viện hiệu ứng","Cửa sổ xuất video"],a:1},{q:"Transition dùng để làm gì?",options:["Thêm nhạc","Tạo hiệu ứng chuyển cảnh giữa các clip","Cắt video","Thêm chữ"],a:1},{q:"Export video với bitrate cao hơn có tác dụng gì?",options:["Video nhẹ hơn","Chất lượng cao hơn nhưng file lớn hơn","Không ảnh hưởng","Video nhanh hơn"],a:1}]}]},
  accounting:{title:"Kế toán Doanh nghiệp",level:"basic",cat:"finance",icon:"📒",img:"accounting.png",desc:"Nền tảng kế toán doanh nghiệp: ghi sổ, lập báo cáo tài chính và phân tích số liệu.",benefits:["Hiểu nguyên lý kế toán kép và hệ thống tài khoản","Lập được Bảng cân đối kế toán và Báo cáo lợi nhuận","Sử dụng phần mềm kế toán MISA hoặc QuickBooks"],modules:[{title:"Accounting Basics",duration:"30 giờ",questions:[{q:"Phương trình kế toán cơ bản là gì?",options:["Tài sản = Nợ phải trả + Vốn chủ sở hữu","Doanh thu - Chi phí = Lợi nhuận","Tài sản = Doanh thu","Nợ = Vốn"],a:0},{q:"Bút toán kép nghĩa là gì?",options:["Ghi 2 lần vào sổ","Mỗi giao dịch ghi Nợ một tài khoản và Có một tài khoản khác","Dùng 2 phần mềm","Kiểm tra 2 lần"],a:1},{q:"Khấu hao tài sản cố định là gì?",options:["Tăng giá trị tài sản","Phân bổ chi phí tài sản theo thời gian sử dụng","Bán tài sản","Mua thêm tài sản"],a:1},{q:"FIFO trong hàng tồn kho nghĩa là gì?",options:["First In First Out - Nhập trước xuất trước","Fast In Fast Out","Final Input Final Output","None"],a:0},{q:"Báo cáo lưu chuyển tiền tệ cho biết điều gì?",options:["Lợi nhuận của công ty","Dòng tiền vào/ra theo hoạt động kinh doanh, đầu tư, tài chính","Số lượng nhân viên","Doanh thu"],a:1},{q:"Tài khoản nào thuộc tài sản ngắn hạn?",options:["Nhà xưởng","Tiền mặt và tiền gửi ngân hàng","Bằng sáng chế","Máy móc"],a:1},{q:"Gross Profit tính như thế nào?",options:["Doanh thu - Chi phí bán hàng","Doanh thu - Giá vốn hàng bán","Lợi nhuận sau thuế","Doanh thu thuần"],a:1},{q:"Audit (Kiểm toán) là gì?",options:["Lập báo cáo tài chính","Kiểm tra độc lập tính chính xác của báo cáo tài chính","Quản lý ngân sách","Đầu tư"],a:1}]}]},
  psychology:{title:"Tâm lý học Ứng dụng",level:"basic",cat:"science",icon:"🧠",img:"psychology.png",desc:"Hiểu hành vi con người, tư duy, cảm xúc và ứng dụng tâm lý học trong cuộc sống và công việc.",benefits:["Hiểu các lý thuyết tâm lý học cơ bản","Ứng dụng tâm lý học trong giao tiếp và quản lý","Nhận biết và quản lý cảm xúc hiệu quả"],modules:[{title:"Applied Psychology",duration:"20 giờ",questions:[{q:"Maslow's Hierarchy of Needs bao gồm mấy tầng nhu cầu?",options:["3","5","7","9"],a:1},{q:"Classical conditioning được khám phá bởi ai?",options:["Freud","Pavlov","Maslow","Jung"],a:1},{q:"Cognitive dissonance là gì?",options:["Sự xung đột giữa niềm tin và hành động","Loại bệnh tâm lý","Phương pháp trị liệu","Lý thuyết học tập"],a:0},{q:"EQ (Emotional Intelligence) bao gồm yếu tố nào?",options:["IQ cao","Nhận thức và quản lý cảm xúc bản thân và người khác","Chỉ số thông minh","Kỹ năng toán học"],a:1},{q:"Confirmation bias là gì?",options:["Xu hướng chỉ chú ý thông tin xác nhận niềm tin có sẵn","Loại trí nhớ","Phương pháp học","Kỹ năng phân tích"],a:0},{q:"Growth mindset khác Fixed mindset ở điểm gì?",options:["Growth: tin khả năng có thể phát triển; Fixed: tin khả năng cố định","Không khác nhau","Fixed tốt hơn","Growth chậm hơn"],a:0},{q:"Active listening bao gồm điều gì?",options:["Chỉ nghe thụ động","Nghe, phản hồi và xác nhận hiểu đúng ý người nói","Ngắt lời người khác","Chỉ gật đầu"],a:1},{q:"Intrinsic motivation là gì?",options:["Động lực từ phần thưởng bên ngoài","Động lực từ bên trong bản thân","Áp lực xã hội","Sợ hình phạt"],a:1}]}]},
  leadership:{title:"Kỹ năng Lãnh đạo",level:"intermediate",cat:"business",icon:"👑",img:"leadership.png",desc:"Phát triển tư duy và kỹ năng lãnh đạo hiệu quả để dẫn dắt đội nhóm thành công.",benefits:["Nắm vững các phong cách lãnh đạo và khi nào áp dụng","Kỹ năng xây dựng và động viên đội nhóm","Giải quyết xung đột và ra quyết định trong tình huống khó"],modules:[{title:"Leadership Excellence",duration:"20 giờ",questions:[{q:"Servant Leadership là phong cách lãnh đạo như thế nào?",options:["Lãnh đạo độc đoán","Lãnh đạo phục vụ - đặt nhu cầu đội nhóm lên trên","Lãnh đạo từ xa","Không lãnh đạo"],a:1},{q:"Delegation hiệu quả yêu cầu điều gì?",options:["Giao việc cho người ít kinh nghiệm nhất","Giao đúng người, đúng việc kèm quyền hạn rõ ràng","Tự làm tất cả","Giao ngẫu nhiên"],a:1},{q:"Feedback hiệu quả nên theo nguyên tắc nào?",options:["Phê bình trước mặt nhiều người","Cụ thể, kịp thời, tập trung vào hành vi không phải tính cách","Chỉ khen, không chê","Im lặng"],a:1},{q:"OKR là công cụ quản lý gì?",options:["Objectives and Key Results - Mục tiêu và Kết quả then chốt","Only Key Results","Operations and Key Roles","Objective Key Report"],a:0},{q:"Emotional Intelligence quan trọng với lãnh đạo vì?",options:["Không quan trọng","Giúp hiểu và quản lý cảm xúc bản thân và đội nhóm","Chỉ cần IQ cao","Giúp tính toán nhanh"],a:1},{q:"Conflict resolution tốt nhất theo cách nào?",options:["Tránh né xung đột","Giải quyết thẳng thắn, tìm giải pháp win-win","Áp đặt ý kiến","Đổ lỗi"],a:1},{q:"Coaching khác Training ở điểm nào?",options:["Coaching dạy kỹ năng cụ thể; Training phát triển tiềm năng","Coaching phát triển tiềm năng qua đặt câu hỏi; Training truyền đạt kiến thức","Giống nhau","Coaching tốn kém hơn"],a:1},{q:"Strategic thinking nghĩa là gì?",options:["Chỉ nghĩ ngắn hạn","Tư duy dài hạn, nhìn toàn cảnh và liên kết các yếu tố","Lập kế hoạch chi tiết","Phân tích số liệu"],a:1}]}]},
  seo:{title:"SEO & Content Marketing",level:"basic",cat:"marketing",icon:"🔍",img:"seo.png",desc:"Tối ưu hóa công cụ tìm kiếm và xây dựng chiến lược nội dung thu hút khách hàng.",benefits:["Tối ưu on-page SEO: từ khóa, title, meta, content","Xây dựng backlink và off-page SEO","Tạo content strategy thu hút và chuyển đổi khách hàng"],modules:[{title:"SEO Fundamentals",duration:"25 giờ",questions:[{q:"Keyword research giúp gì?",options:["Thiết kế website","Xác định từ khóa người dùng tìm kiếm để tạo content phù hợp","Viết code","Chạy quảng cáo"],a:1},{q:"Backlink là gì?",options:["Link nội bộ trong website","Link từ website khác trỏ về website của bạn","Link mạng xã hội","Link quảng cáo"],a:1},{q:"Meta description quan trọng với SEO vì?",options:["Ảnh hưởng trực tiếp ranking","Mô tả hiển thị trên SERP giúp tăng CTR","Bắt buộc phải có","Không quan trọng"],a:1},{q:"Core Web Vitals đo lường điều gì?",options:["Số từ khóa","Trải nghiệm người dùng: tốc độ tải, tương tác, ổn định trực quan","Số backlink","Traffic"],a:1},{q:"Long-tail keyword là gì?",options:["Từ khóa ngắn","Cụm từ dài hơn, ít cạnh tranh hơn và traffic chất lượng hơn","Từ khóa phổ biến nhất","Từ khóa tiếng Anh"],a:1},{q:"E-E-A-T trong SEO nghĩa là gì?",options:["Experience-Expertise-Authoritativeness-Trustworthiness","Engagement-Exposure-Awareness-Traffic","None","Không quan trọng"],a:0},{q:"301 Redirect dùng khi nào?",options:["Khi server lỗi","Chuyển hướng vĩnh viễn từ URL cũ sang URL mới","Tạo trang mới","Xóa trang"],a:1},{q:"XML Sitemap giúp gì?",options:["Trang trí website","Giúp search engine crawl và index website hiệu quả hơn","Tăng tốc server","Bảo mật"],a:1}]}]},
  ecommerce:{title:"Kinh doanh Online & E-commerce",level:"basic",cat:"business",icon:"🛒",img:"course_business_1778119185318.png",desc:"Xây dựng cửa hàng trực tuyến thành công từ lựa chọn sản phẩm đến vận hành và marketing.",benefits:["Xây dựng cửa hàng Shopify/WooCommerce chuyên nghiệp","Chiến lược tìm sản phẩm và nhà cung cấp","Vận hành, marketing và tối ưu chuyển đổi"],modules:[{title:"E-commerce Business",duration:"20 giờ",questions:[{q:"Conversion rate trong e-commerce là gì?",options:["Tỷ lệ % người mua trên tổng số người truy cập","Tỷ lệ chuyển đổi tiền tệ","Tốc độ tải trang","Số đơn hàng"],a:0},{q:"Dropshipping là mô hình kinh doanh gì?",options:["Bán hàng có kho dự trữ lớn","Bán hàng mà không cần kho, nhà cung cấp giao thẳng cho khách","Sản xuất hàng tự dùng","Nhập hàng bulk"],a:1},{q:"Cart abandonment rate cao cần làm gì?",options:["Tắt trang web","Gửi email nhắc nhở và tối ưu checkout process","Tăng giá","Xóa giỏ hàng"],a:1},{q:"AOV (Average Order Value) là chỉ số gì?",options:["Giá trị đơn hàng trung bình","Số đơn hàng trung bình","Lợi nhuận trung bình","Traffic trung bình"],a:0},{q:"Upsell khác Cross-sell ở điểm nào?",options:["Upsell: đề nghị sản phẩm tốt hơn; Cross-sell: đề nghị sản phẩm bổ sung","Giống nhau","Upsell rẻ hơn","Cross-sell cao hơn"],a:0},{q:"Customer Lifetime Value (LTV) quan trọng vì?",options:["Đo tổng giá trị khách hàng mang lại trong toàn bộ thời gian mua hàng","Đo 1 đơn hàng","Đo chi phí marketing","Đo traffic"],a:0},{q:"A/B Testing trong e-commerce giúp gì?",options:["Test phần cứng","So sánh 2 phiên bản trang để tìm phiên bản chuyển đổi tốt hơn","Test tốc độ","Kiểm tra bảo mật"],a:1},{q:"Nền tảng nào phổ biến để tạo cửa hàng online?",options:["Microsoft Word","Shopify, WooCommerce, Haravan","Adobe Photoshop","AutoCAD"],a:1}]}]},
  nutrition:{title:"Dinh dưỡng & Sức khỏe",level:"basic",cat:"health",icon:"🥗",img:"course_python_1778118354919.png",desc:"Hiểu khoa học dinh dưỡng để xây dựng chế độ ăn lành mạnh và phong cách sống khỏe mạnh.",benefits:["Hiểu vai trò của macro và micronutrients","Lập kế hoạch dinh dưỡng phù hợp mục tiêu sức khỏe","Phân biệt thông tin dinh dưỡng đúng và sai trên mạng"],modules:[{title:"Nutrition Science",duration:"20 giờ",questions:[{q:"Macronutrients gồm những chất nào?",options:["Vitamin và khoáng chất","Protein, Carbohydrate và Chất béo","Nước và muối","Enzyme"],a:1},{q:"Chỉ số BMI đo lường điều gì?",options:["Tỷ lệ mỡ cơ thể chính xác","Ước tính tỷ lệ cân nặng/chiều cao để đánh giá cân nặng","Lượng cơ bắp","Mật độ xương"],a:1},{q:"Fiber (chất xơ) có tác dụng gì?",options:["Cung cấp năng lượng chính","Hỗ trợ tiêu hóa và điều hòa đường huyết","Xây dựng cơ bắp","Không có tác dụng"],a:1},{q:"Nước đóng vai trò gì trong cơ thể?",options:["Chỉ giải khát","Vận chuyển chất dinh dưỡng, điều hòa thân nhiệt, loại bỏ độc tố","Cung cấp năng lượng","Xây dựng cơ bắp"],a:1},{q:"Protein cần thiết cho điều gì?",options:["Chỉ cho vận động viên","Xây dựng và sửa chữa mô cơ, tạo enzyme và hormone","Cung cấp năng lượng nhanh","Lưu trữ vitamin"],a:1},{q:"Calorie deficit nghĩa là gì?",options:["Ăn quá nhiều","Tiêu thụ ít calo hơn lượng đốt cháy - điều kiện để giảm cân","Thiếu vitamin","Ăn đủ calo"],a:1},{q:"Omega-3 có nhiều trong thực phẩm nào?",options:["Khoai tây chiên","Cá hồi, hạt chia, quả óc chó","Bánh ngọt","Nước ngọt"],a:1},{q:"Glycemic Index (GI) đo lường điều gì?",options:["Lượng calo trong thực phẩm","Tốc độ thực phẩm làm tăng đường huyết","Hàm lượng protein","Lượng chất xơ"],a:1}]}]},
  photgraphy:{title:"Nhiếp ảnh Cơ bản",level:"basic",cat:"design",icon:"📷",img:"course_webdev_1778118376821.png",desc:"Học cách chụp ảnh đẹp từ kỹ thuật cơ bản đến hậu kỳ chỉnh sửa với Lightroom.",benefits:["Hiểu tam giác phơi sáng: ISO, Aperture, Shutter Speed","Nắm vững quy tắc bố cục ảnh","Chỉnh sửa ảnh chuyên nghiệp với Adobe Lightroom"],modules:[{title:"Photography Basics",duration:"20 giờ",questions:[{q:"Aperture (khẩu độ) ảnh hưởng đến điều gì?",options:["Màu sắc ảnh","Độ sâu trường ảnh và lượng ánh sáng vào","Tốc độ chụp","ISO"],a:1},{q:"ISO cao ảnh hưởng như thế nào?",options:["Ảnh tối hơn","Ảnh sáng hơn nhưng nhiễu hơn","Không ảnh hưởng","Ảnh mờ hơn"],a:1},{q:"Rule of Thirds là quy tắc gì?",options:["Chia ảnh thành 3 phần bằng nhau và đặt chủ thể ở điểm giao","Chụp 3 kiểu ảnh","Dùng 3 màu chính","Phơi sáng 3 giây"],a:0},{q:"RAW format khác JPEG ở điểm nào?",options:["RAW nhỏ hơn","RAW lưu toàn bộ dữ liệu, chỉnh sửa tốt hơn nhưng file lớn","JPEG tốt hơn","Giống nhau"],a:1},{q:"White balance dùng để làm gì?",options:["Chỉnh độ sáng","Điều chỉnh nhiệt độ màu để màu sắc trung thực","Tăng contrast","Giảm nhiễu"],a:1},{q:"Golden hour là thời điểm nào trong ngày?",options:["12 giờ trưa","Ngay sau bình minh và trước hoàng hôn - ánh sáng đẹp nhất","Đêm khuya","4 giờ sáng"],a:1},{q:"Depth of Field nông (shallow) tạo ra hiệu ứng gì?",options:["Toàn ảnh sắc nét","Chủ thể sắc nét, phông nền mờ (bokeh)","Ảnh tối","Ảnh rộng hơn"],a:1},{q:"Histogram trong nhiếp ảnh cho biết điều gì?",options:["Số ảnh đã chụp","Phân bố độ sáng tối trong ảnh","Màu sắc chính xác","Tốc độ máy ảnh"],a:1}]}]}
};

// Merge all courses
const allExtraCourses = Object.assign({}, extraCourses, extraCourses2);

// Render extra course cards into the grid
function renderExtraCourses() {
  const grid = document.getElementById('courseGrid');
  if (!grid || typeof allExtraCourses === 'undefined') return;
  const levelMap = {basic:'Cơ bản',intermediate:'Trung cấp',advanced:'Nâng cao'};
  const imgMap = {technology:'course_ai_1778118398059.png',design:'course_webdev_1778118376821.png',marketing:'course_business_1778119185318.png',finance:'course_aicert_1778119251405.png',business:'course_business_1778119185318.png',data:'course_data_1778119207331.png',language:'course_python_1778118354919.png',science:'course_datamodeling_1778119228978.png',health:'course_python_1778118354919.png'};
  Object.entries(allExtraCourses).forEach(([id, course]) => {
    const img = course.img;
    const lvl = course.level || 'basic';
    const card = document.createElement('div');
    card.className = 'course-card'; card.dataset.cat = course.cat; card.dataset.level = course.level || 'basic';
    card.dataset.level = lvl;
    card.innerHTML = `
      <div class="course-image">
        <img src="images/${img}" alt="${course.title}">
        <span class="badge ${lvl}">${levelMap[lvl]||lvl}</span>
      </div>
      <div class="course-content">
        <h3>${course.icon} ${course.title}</h3>
        <p class="instructor">Bởi LearnX Instructor</p>
        <div class="course-meta">
          <span><i class="fas fa-star"></i> 4.8 (500+)</span>
          <span><i class="fas fa-clock"></i> ${course.modules[0].duration}</span>
        </div>
        <div class="course-footer">
          <span class="price">Miễn phí</span>
          <button class="btn-enroll" onclick="openCourseModal('${id}')">Học &amp; Quiz</button>
        </div>
      </div>`;
    grid.appendChild(card);
    // Add to coursesData
    if (typeof coursesData !== 'undefined') coursesData[id] = course;
  });
}
document.addEventListener('DOMContentLoaded', renderExtraCourses);


// Generate AI videos mapping object
const AI_VIDEOS = {
  python: 'video_python.mp4',
  webdev: 'video_webdev.mp4',
  react: 'video_react.mp4',
  ai: 'video_ai.mp4',
  business: 'video_business.mp4',
  datamngt: 'video_datamngt.mp4',
  datamodel: 'video_datamodel.mp4',
  aicert: 'video_aicert.mp4',
  cybersec: 'video_cybersec.mp4',
  cloud: 'video_cloud.mp4',
  devops: 'video_devops.mp4',
  uxui: 'video_uxui.mp4',
  marketing: 'video_marketing.mp4',
  finance: 'video_finance.mp4',
  excel: 'video_excel.mp4',
  english: 'video_english.mp4',
  project: 'video_project.mp4',
  photoshop: 'video_photoshop.mp4',
  flutter: 'video_flutter.mp4',
  blockchain: 'video_blockchain.mp4',
  videoediting: 'video_videoediting.mp4',
  accounting: 'video_accounting.mp4',
  psychology: 'video_psychology.mp4',
  leadership: 'video_leadership.mp4',
  seo: 'video_seo.mp4',
  ecommerce: 'video_ecommerce.mp4',
  nutrition: 'video_nutrition.mp4',
  photgraphy: 'video_photography.mp4'
};
